version: '3.8'
services:
  # PHP Service
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./project:/var/www/symfony

  # Nginx Service
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./project:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PostgreSQL Service
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: DataB
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    volumes:
      - ./dbData:/var/lib/postgresql/data

volumes:
  pgdata:
